apiVersion: v1
kind: Service
metadata:
  name: service-uscip-api
spec:
  selector:
    app: uscip-api
  ports:
    - name: api
      port: 3000
      targetPort: 3000
    - name: apidoc
      port: 3030
      targetPort: 3030